### ISSUE TITLE
AttributeError: 'module' object has no attribute 'qr_code_scanner'

### ISSUE THREAD

**Issue by rocchidavide** [Polyconseil/zbarlight#8]
When I import zbarlight in python shell or in a python script, I get this error:

```
>>> import zbarlight
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "zbarlight.py", line 11, in <module>
    codes = zbarlight.scan_codes('qrcode', image)
AttributeError: 'module' object has no attribute 'scan_codes'
```

I have installed zbar previously with brew and zbarlight with pip. zbarlight version: 1.0.2

**Comment by rbarrois** [comment]
Hi,

You seem to have a file named ``zbarlight.py`` in your local folder.
Thus, when running ``import zbarlight``, Python imports the *local* file instead of the ``zbarlight`` module.

However, that code is, in turn, importing ``zbarlight`` — itself.

Try renaming that file to, for instance, ``zbarlight_demo.py``; that should fix your issue.

**Comment by dbaty** [comment]
I'll suppose that it was indeed the issue.
